
#############################################[ 公共配置 ]#############################################
spring:
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true

  # 项目静态资源路径
  mvc:
    static-path-pattern: /static/**

  # 项目logo----浏览器标签上的那个
  favicon:
    enabled: false

  # thymeleaf 模板引擎配置
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html

  # AOP配置
  aop:
    auto: true

---
#############################################[ 开发环境 ]#############################################
# servlet配置
server:
  servlet:
    context-path: /manage
    session:
      timeout: 1800
  port: 9874

# mybatis 配置
mybatis:
  # config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

# 日志配置  
logging:
  config: classpath:config/log/log4j.xml
  level:
    com.xnote.manage.modules.**.service.impl: trace

###==[ spring配置 ]==###
spring:
  profiles: dev

  # 上传文件设置
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  # cache 设置
  cache:
    type: redis

  # RabbitMQ 配置
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

  # redis链接设置
  redis:
    database: 14
    host: 127.0.0.1
    port: 6379
    password: 1qaz@wsX
    timeout: 5000
    jedis:
      pool:
        max-idle: 500
        min-idle: 50
        max-active: 1000
        max-wait: 2000

  # 数据源配置
  datasource:
    username: root
    password: 1qaz@wsX
    url: jdbc:mysql://127.0.0.1:3306/xnote?useUnicode=true&characterEncoding=UTF-8&transformedBitIsBoolean=true&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
    # &useAffectedRows=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    #   数据源其他配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

  # 项目配置
xnote:
  licence: # 许可配置
    path: /lic/licence.lic
  # 资源图标路径
  resIconPath: E:/_WORKSPACE/IDEA/XNOTE/resources/icon/
  # 资源储存路径
  resStorePath: E:/_WORKSPACE/IDEA/XNOTE/resources/utils/

---
#############################################[ 测试环境 ]#############################################
# servlet配置
server:
  servlet:
    context-path: /manage-test
    session:
      timeout: 600
  port: 8090

# mybatis 配置
mybatis:
  # config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

# 日志配置  
logging:
  config: classpath:config/log/log4j.xml
  level:
    com.xnote.manage.modules.**.service.impl: trace

###==[ spring配置 ]==###
spring:
  profiles: test

  # 上传文件设置
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  # cache 设置
  cache:
    type: redis

  # RabbitMQ 配置
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin

  # redis链接设置
  redis:
    database: 14
    host: 127.0.0.1
    port: 6379
    password: root
    timeout: 5000
    jedis:
      pool:
        max-idle: 500
        min-idle: 50
        max-active: 1000
        max-wait: 2000

  # 数据源配置
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/xnote?useUnicode=true&characterEncoding=UTF-8&transformedBitIsBoolean=true&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
    # &useAffectedRows=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    #   数据源其他配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

# 项目配置
xnote:
  licence: # 许可配置
    path: /lic/licence.lic
  # 资源图标路径
  resIconPath: E:/_WORKSPACE/IDEA/XNOTE/resources/icon/
  # 资源储存路径
  resStorePath: E:/_WORKSPACE/IDEA/XNOTE/resources/utils/

---
#############################################[ 生产环境 ]#############################################
server:
  servlet:
    context-path: /xnmanage
    session:
      timeout: 3600
  port: 18765

# mybatis 配置
mybatis:
  # config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

# 日志配置  
logging:
  config: classpath:config/log/log4j.xml
  level:
    com.xnote.manage.modules.**.service.impl: trace

###==[ spring配置 ]==###
spring:
  profiles: prod

  # 上传文件设置
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  # cache 设置
  cache:
    type: redis

  # RabbitMQ 配置
  rabbitmq:
    host: 118.24.21.83
    port: 5672
    username: admin
    password: admin

  # redis链接设置
  redis:
    database: 14
    host: 118.24.21.83
    port: 6379
    password: root
    timeout: 5000
    jedis:
      pool:
        max-idle: 500
        min-idle: 50
        max-active: 1000
        max-wait: 2000

  # 数据源配置
  datasource:
    username: root
    password: root
    url: jdbc:mysql://118.24.21.83:3306/XNOTE?useUnicode=true&characterEncoding=UTF-8&transformedBitIsBoolean=true&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
    # &useAffectedRows=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    #   数据源其他配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

# 项目配置
xnote:
  licence: # 许可配置
    path: /lic/licence.lic
  # 资源图标路径
  resIconPath: E:/_WORKSPACE/IDEA/XNOTE/resources/icon/
  # 资源储存路径
  resStorePath: E:/_WORKSPACE/IDEA/XNOTE/resources/utils/